### ISSUE TITLE
Add new argument to doLOBscreen function which will allow users to retain rejected/unidentified features

### ISSUE THREAD

**Issue by joefutrelle** [vanmooylipidomics/LOBSTAHS#12]
(anything not positively ID’d by the various LOBSTAHS criteria right now gets discarded)

Useful for untargeted mode analysis

**Comment by jamesrco** [comment]
Necessity is the mother of invention. Should have a solution ready for this one by the end of the day.

**Comment by jamesrco** [comment]
And... voilà! 56549488337b86ab9edd2a7bf85a265271b54ca7...e0c615ee380e17442537f5a4173ff94c6ccf1877 incorporate new arguments `retain.unidentified` into `doLOBscreen` and `include.unidentified` into `getLOBpeaklist`. Also updated manual pages for both functions and the show method for the `LOBSet` object class (to make it backward-compatible with older data objects). Lastly, update the vignette to reflect incorporation of the new feature. Will close this one out, but feel free to re-open if I missed a bug someplace. I did a complete R CMD check but that doesn't always catch everything.
