### ISSUE TITLE
Error screening based on retention time

### ISSUE THREAD

**Issue by ricoderks** [vanmooylipidomics/LOBSTAHS#3]
Hi James,

I tried to use my retention time window file, but I get this error :

```
Error in doLOBscreen(xsetA, polarity = "positive", database = NULL, remove.iso = TRUE,  : 
  Could not find unique field 'lipid_class' in user's retention time data.
```

The column lipid_class is there. I used your file and adjusted to times. Looking at the code of doLOBscreen() it seems that the file is not loaded.

Cheers, Rico

**Comment by jamesrco** [comment]
Looks like this works properly now that the other error was corrected
