### ISSUE TITLE
Transfer formal Bioconductor ownership/maintainer responsibilities to @hholm

### ISSUE THREAD

**Issue by jamesrco** [vanmooylipidomics/LOBSTAHS#33]
Transfer to @hholm will require Henry uploading his public key to Bioconductor, some changes in the package documentation

What else?

**Comment by hholm** [comment]
Hey @jamesrco - all credentials are working fine and I just pushed an update to Bioconductor. Thanks for help with the transfer and thanks for trusting me with maintaining LOBSTAHS!
